server:
  port: 9090
  tomcat:
    max-threads: 2000
    max-connections: 2000
  connection-timeout: 30000ms

spring:
  profiles:
    active: dev


  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://rm-2ze1oz4pi4woc067syo.mysql.rds.aliyuncs.com:3306/miu?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
      username: root
      password: sfOPFwf$#%^&*
      pool-name: DatebookHikariCP
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sfOPFwf$#%^&*
    url: jdbc:mysql://rm-2ze1oz4pi4woc067syo.mysql.rds.aliyuncs.com:3306/miu?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&&useSSL=false


  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 1
        min-idle: 8
    timeout: 1000ms


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_empty
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    #deserialization: true


#微信支付
defaultAppId: wx097eb9f69920db49
paterKey: 123fdsaJHYUTREWQOKLJGCCBNM654389
mchId: 1503679961
attach: stg
domain: http://testwepay.free.idcfengye.com

#支付宝
aliPay:
  appId: 2018090761263694
  privateKey:
  publicKey:
  notifyUrl: /AliPay/aliPayNotify
  returnUrl: /AliPay/aliPayReturn
  gatewayUrl: https://openapi.alipay.com/gateway.do
  signType: RSA2

#阿里云OSS
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAIHn6oIue9yxds
    accessKeySecret: 38R8crqNQKNP5AT6H7ZOLy9IZ7sQRG



#分页设置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


#log
logging:
  config: classpath:logback.xml